# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=500)),
                ('speech', models.CharField(max_length=2000)),
                ('tendency', models.CharField(max_length=500)),
                ('interview_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='interview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Question'),
        ),
        migrations.AddField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
