# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.NullBooleanField(),
        ),
    ]
