# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
