# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180503_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fname',
            field=models.CharField(blank=True, default='a', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='groupid',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='lname',
            field=models.CharField(blank=True, default='d', max_length=10),
        ),
    ]
