# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180524_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendencyresult',
            name='interview_count',
            field=models.IntegerField(default=0),
        ),
    ]
