# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180510_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interview',
            name='emotion',
            field=models.TextField(),
        ),
    ]
