# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0003_auto_20180514_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='interview',
            name='speech',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interview',
            name='tendency',
            field=models.TextField(),
        ),
    ]
