# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180503_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='groupid',
            new_name='groupId',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='ldate',
            new_name='loginDate',
        ),
        migrations.AddField(
            model_name='users',
            name='birthDate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
