# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_interview_headpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
